### ISSUE TITLE
Play-Button schwierig anzuklicken

### ISSUE THREAD

**Issue by dsterle** [dsterle/EPWS2019PawlowskiSterle#53]
Mir ist aufgefallen, dass der play/pause-button nur reagiert, wenn man direkt auf das Symbol tippt / klickt, es wäre aber benutzerfreundlicher, wenn die onclick Funktion aktiviert werden würde, wenn man auf den button tippt / klickt.

**Comment by hendrikpawlowski** [comment]
Ist verbessert
